# Generated by Django 5.0 on 2023-12-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='clinic/images/')),
                ('icon', models.ImageField(upload_to='clinic/images/')),
                ('about_clinic', models.TextField(blank=True)),
                ('address', models.CharField(max_length=100)),
                ('work_time', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('vet', models.ManyToManyField(related_name='clinic', to='vet.vet', verbose_name='Ветеринары')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='clinic/images/')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinic.clinic', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
