# Generated by Django 5.0 on 2023-12-21 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.BooleanField(null=True)),
                ('castration', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Здоровье',
                'verbose_name_plural': 'Здоровье',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='PetPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet/images/')),
                ('is_main', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Фото питомца',
                'verbose_name_plural': 'Фото питомца',
            },
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinarian_check', models.DateField()),
                ('vaccination', models.DateField()),
                ('deworming', models.DateField()),
                ('tick_flea_treatmen', models.DateField()),
            ],
            options={
                'verbose_name': 'Процедуры',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Де', 'Дерматит'), ('По', 'Заболевание почек'), ('Су', 'Заболевание суставов'), ('Ож', 'Ожирение'), ('Мо', 'Мочекаменная болезнь'), ('Са', 'Сахарный диабет'), ('Се', 'Сердечная недостаточность'), ('Чу', 'Чувствительное пищеварение'), ('Бе', 'Беременность'), ('Во', 'Восстановление после болезни')], max_length=25)),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pet.health', verbose_name='Особенности')),
            ],
            options={
                'verbose_name': 'Особенности',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='pet.kind', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('weight', models.FloatField()),
                ('wool_type', models.CharField(choices=[('К', 'Короткая'), ('С', 'Средняя'), ('Д', 'Длинная')], max_length=8)),
                ('chip_number', models.CharField(max_length=18)),
                ('origin', models.CharField(choices=[('Ул', 'Подобран на улице'), ('За', 'Куплен у заводчика'), ('Пр', 'Взят из приюта'), ('Вы', 'Куплен на выставке'), ('Ма', 'Куплен в магазине'), ('Бо', 'Спизжен у бомжей')], max_length=18)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pet.breed', verbose_name='Питомец')),
                ('health', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pet.health', verbose_name='Здоровье')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='pet.kind', verbose_name='Питомец')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
    ]
